CREATE TABLE IF NOT EXISTS USER (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS OTP (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    CODE VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
);