INSERT INTO USER VALUES (1, 'bob', '$2y$12$dmsZlO2s6coyY/yuvPLQmeV6NOwBOYw6NBNuHEYH7qSLs2E9GOwWe', 'BCRYPT');
INSERT INTO AUTHORITY VALUES (1, 1, 'READ');
INSERT INTO AUTHORITY VALUES (2, 1, 'WRITE');
INSERT INTO PRODUCT VALUES (1, 'Beer', '3.50', 'USD');
