INSERT INTO USER VALUES (1, 'bob', '$2y$12$CziPClQZvoenmY6M/PxDJOoa0Aq5hSujbu8mo84eAvooWsVX2rTg2', 'BCRYPT');
INSERT INTO AUTHORITY VALUES (1, 1, 'READ');
INSERT INTO AUTHORITY VALUES (2, 1, 'WRITE');
INSERT INTO PRODUCT VALUES (1, 'Beer', '3.50', 'USD');
