CREATE TABLE IF NOT EXISTS USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    AUTHORITY VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
);